### ISSUE TITLE
Share simplification folder

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/push-simplification-for-generalization#2]
@erp12 should share his GDrive `simplification-data` folder with us to make it easier to run the R scripts.

If there's a storage limit issue, I'd be happy to host the files since the U of MN's contract with Google gives us effectively unlimited GDrive storage.

**Comment by erp12** [comment]
I am fine with either. Do you expect to write a bunch more files or images to that folder?

**Comment by NicMcPhee** [comment]
I have no idea about the files. There could be more images, but ultimately we probably want those in the repo rather than GDrive since they're a key part of what we're publishing.

**Comment by erp12** [comment]
I modified the viz script to point to @NicMcPhee 's GDrive folder in 7248f24906a5bdc45c437c9f07e6d1eae462c202.

Closing this issue because I think we are good. Let me know if I am overlooking something.
