### ISSUE TITLE
Align pre-simplification problem size density plots by problem

### ISSUE THREAD

**Issue by NicMcPhee** [NicMcPhee/push-simplification-for-generalization#4]
It would be nice to have [the two density plots for each problem](https://push-language.hampshire.edu/t/gecco-2017-simplification-for-generalization/660/98?u=mcphee) side-by-side if possible. We may not be able to fit all of these if we do this, but it would be good to see what happens.

**Comment by erp12** [comment]
Done in 16a3bd35193fdc0a7ba1b9e5c09629a067f6c06c
